//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS_V1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class IMS_V1Entities : DbContext
    {
        public IMS_V1Entities()
            : base("name=IMS_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABC_Lookup> ABC_Lookup { get; set; }
        public DbSet<APlusItem> APlusItems { get; set; }
        public DbSet<Attribute_Lookup> Attribute_Lookup { get; set; }
        public DbSet<AttributeType> AttributeTypes { get; set; }
        public DbSet<Buyer> Buyers { get; set; }
        public DbSet<CategoryAttribute> CategoryAttributes { get; set; }
        public DbSet<CategoryClass> CategoryClasses { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<FFLType> FFLTypes { get; set; }
        public DbSet<FineLineClass> FineLineClasses { get; set; }
        public DbSet<Freight_Lookup> Freight_Lookup { get; set; }
        public DbSet<ImportedItem> ImportedItems { get; set; }
        public DbSet<ImportFile> ImportFiles { get; set; }
        public DbSet<ItemAttribute> ItemAttributes { get; set; }
        public DbSet<ItemDescriptionOrder> ItemDescriptionOrders { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemTextAttachment> ItemTextAttachments { get; set; }
        public DbSet<ItemWareHous> ItemWareHouses { get; set; }
        public DbSet<PrintedItemsForAPlu> PrintedItemsForAPlus { get; set; }
        public DbSet<ReplacementItem> ReplacementItems { get; set; }
        public DbSet<ReplacementItemCode> ReplacementItemCodes { get; set; }
        public DbSet<SubClass> SubClasses { get; set; }
        public DbSet<UM_Lookup> UM_Lookup { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<VendorTradeName> VendorTradeNames { get; set; }
        public DbSet<WareHouse_Lookup> WareHouse_Lookup { get; set; }
        public DbSet<WebCode> WebCodes { get; set; }
        public DbSet<zManufacturersLogo> zManufacturersLogoes { get; set; }
        public DbSet<zManufacturersLogo_History> zManufacturersLogo_History { get; set; }
    
        public virtual int AddLongDescription(Nullable<int> itemId, string text, Nullable<int> userId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLongDescription", itemIdParameter, textParameter, userIdParameter);
        }
    
        public virtual ObjectResult<APlusImport_ITBAL_Result> APlusImport_ITBAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APlusImport_ITBAL_Result>("APlusImport_ITBAL");
        }
    
        public virtual ObjectResult<APlusImport_ITMST_Result> APlusImport_ITMST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<APlusImport_ITMST_Result>("APlusImport_ITMST");
        }
    
        public virtual ObjectResult<GetExistingLongDescriptions_Result> GetExistingLongDescriptions(Nullable<int> itemId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExistingLongDescriptions_Result>("GetExistingLongDescriptions", itemIdParameter);
        }
    
        public virtual ObjectResult<GetExistingWareHousesList_Result> GetExistingWareHousesList(Nullable<int> item_Id)
        {
            var item_IdParameter = item_Id.HasValue ?
                new ObjectParameter("Item_Id", item_Id) :
                new ObjectParameter("Item_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetExistingWareHousesList_Result>("GetExistingWareHousesList", item_IdParameter);
        }
    
        public virtual ObjectResult<GetLongDescription_Result> GetLongDescription(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLongDescription_Result>("GetLongDescription", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewItem(Nullable<int> itemId, Nullable<int> userId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewItem", itemIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<GetRemainingAttributeTypes_Result> GetRemainingAttributeTypes(Nullable<int> itemId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRemainingAttributeTypes_Result>("GetRemainingAttributeTypes", itemIdParameter);
        }
    
        public virtual int UpdateItemDescription(Nullable<int> item_Id, string newDescription, Nullable<int> userId)
        {
            var item_IdParameter = item_Id.HasValue ?
                new ObjectParameter("Item_Id", item_Id) :
                new ObjectParameter("Item_Id", typeof(int));
    
            var newDescriptionParameter = newDescription != null ?
                new ObjectParameter("NewDescription", newDescription) :
                new ObjectParameter("NewDescription", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateItemDescription", item_IdParameter, newDescriptionParameter, userIdParameter);
        }
    
        public virtual int UpdateLongDescription(Nullable<int> id, string text)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var textParameter = text != null ?
                new ObjectParameter("Text", text) :
                new ObjectParameter("Text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLongDescription", idParameter, textParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewSimpleItem(Nullable<int> itemId, Nullable<int> userId)
        {
            var itemIdParameter = itemId.HasValue ?
                new ObjectParameter("ItemId", itemId) :
                new ObjectParameter("ItemId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewSimpleItem", itemIdParameter, userIdParameter);
        }
    }
}
